# Generated by Django 4.2.5 on 2024-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_cliente_user_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliario',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
    ]
