# Generated by Django 4.2.5 on 2024-06-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_pedido_estado_pedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domiciliario',
            old_name='medio_transporte',
            new_name='medio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='domiciliario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.domiciliario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='horario_disponibilidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='domiciliario',
            name='licencia_conduccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
